src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sous_titre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $categorie = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getSousTitre(): ?string
    {
        return $this->sous_titre;
    }

    public function setSousTitre(?string $sous_titre): self
    {
        $this->sous_titre = $sous_titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Filtre;
use App\Form\FiltreType;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product' , methods: ['POST', 'GET'])]
    public function index(ProduitRepository $produitRepository, Request $request): Response
    {
        $filtre = new Filtre();

        $form = $this->createForm(FiltreType::class, $filtre);
        $form->handleRequest($request); 

        if($form->isSubmitted() && $form->isValid())
        {
            //$search = $form->getData();
            //d($search);

            $produits = $produitRepository->findByFiltre($filtre);
        }else{
            $produits = $produitRepository->findAll();
        }

        return $this->render('product/index.html.twig', [
            'produits' => $produits,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/show-produit/{slug}', name: 'app_show_product')]
    public function show($slug, ProduitRepository $produitRepository): Response
    {
        $produit = $produitRepository->findOneBySlug($slug);        
        if(!$produit){
            return $this->redirectToRoute('app_product');
        }
        return $this->render('product/show.html.twig', [
            'produit' => $produit,
        ]);
    }
}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-3">
            <h3>Filtre</h3>
            {{ form_start(form) }}
                <div>{{ form_row(form.nom) }}</div>
                <div>{{ form_row(form.categorie) }}</div>
                <div><button class="btn btn-info btn-sm">{{ button_label|default('Chercher') }}<i class="fa fa-search p-1"></i></button></div>
            {{ form_end(form) }}
        </div>
        <div class="col-md-9">  
            <h3>Nos produits</h3>
            <div class="row">
                {% for produit in produits %}
                    <div class="col-md-4 p-2 text-center">
                        <div class="card" >
                            <img class="card-img-top" src="{{asset('image_produits/' ~ produit.illustration)}}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">{{produit.nom }}</h5>
                                <p class="card-text">{{ produit.sousTitre}}</p>
                                <p><span class="card-text text-break span">{{ (produit.prix/100) |number_format(2)}} €</span></p>
                                <a href="{{path('app_show_product', { slug : produit.slug })}}" class="btn btn-primary">Détails</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
 

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row show_produit">
        <div class="col-md-5">
            <img src="{{asset('image_produits/' ~ produit.illustration )}}" alt="{{produit.nom }}" class="img-fluid">
        </div>
        <div class="col-md-7 my-auto">
            <h3> {{ produit.nom }}</h3> 
            <p>{{produit.sousTitre }}</p>
            <p><span class="card-text text-break span">{{ (produit.prix/100) | number_format(2)}} €</span></p>
            <hr>
            <p>{{ produit.description }}</p>
            <hr>
            <a href="{{path('app_add_cart', { 'id' : produit.id })}}" class="btn btn-primary btn-sm">Ajouter au panier</a>
        </div>
    </div>
{% endblock %}